/*
 * This file is generated by jOOQ.
 */
package DB.Tables_Test.tables.records;


import DB.Tables_Test.tables.Alert;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AlertRecord extends UpdatableRecordImpl<AlertRecord> implements Record3<Integer, String, String> {

    private static final long serialVersionUID = -701331490;

    /**
     * Setter for <code>fwdb_test.alert.alert_id</code>.
     */
    public void setAlertId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>fwdb_test.alert.alert_id</code>.
     */
    public Integer getAlertId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>fwdb_test.alert.username</code>.
     */
    public void setUsername(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>fwdb_test.alert.username</code>.
     */
    public String getUsername() {
        return (String) get(1);
    }

    /**
     * Setter for <code>fwdb_test.alert.notification</code>.
     */
    public void setNotification(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>fwdb_test.alert.notification</code>.
     */
    public String getNotification() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<Integer, String, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Integer, String, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Alert.ALERT.ALERT_ID;
    }

    @Override
    public Field<String> field2() {
        return Alert.ALERT.USERNAME;
    }

    @Override
    public Field<String> field3() {
        return Alert.ALERT.NOTIFICATION;
    }

    @Override
    public Integer component1() {
        return getAlertId();
    }

    @Override
    public String component2() {
        return getUsername();
    }

    @Override
    public String component3() {
        return getNotification();
    }

    @Override
    public Integer value1() {
        return getAlertId();
    }

    @Override
    public String value2() {
        return getUsername();
    }

    @Override
    public String value3() {
        return getNotification();
    }

    @Override
    public AlertRecord value1(Integer value) {
        setAlertId(value);
        return this;
    }

    @Override
    public AlertRecord value2(String value) {
        setUsername(value);
        return this;
    }

    @Override
    public AlertRecord value3(String value) {
        setNotification(value);
        return this;
    }

    @Override
    public AlertRecord values(Integer value1, String value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AlertRecord
     */
    public AlertRecord() {
        super(Alert.ALERT);
    }

    /**
     * Create a detached, initialised AlertRecord
     */
    public AlertRecord(Integer alertId, String username, String notification) {
        super(Alert.ALERT);

        set(0, alertId);
        set(1, username);
        set(2, notification);
    }
}
