/*
 * This file is generated by jOOQ.
 */
package DB.Tables_Test.tables.records;


import DB.Tables_Test.tables.EventSwitchPlayers;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EventSwitchPlayersRecord extends UpdatableRecordImpl<EventSwitchPlayersRecord> implements Record6<Integer, Integer, String, String, String, Integer> {

    private static final long serialVersionUID = 824466803;

    /**
     * Setter for <code>fwdb_test.event_switch_players.event_id</code>.
     */
    public void setEventId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>fwdb_test.event_switch_players.event_id</code>.
     */
    public Integer getEventId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>fwdb_test.event_switch_players.game_id</code>.
     */
    public void setGameId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>fwdb_test.event_switch_players.game_id</code>.
     */
    public Integer getGameId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>fwdb_test.event_switch_players.team_name</code>.
     */
    public void setTeamName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>fwdb_test.event_switch_players.team_name</code>.
     */
    public String getTeamName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>fwdb_test.event_switch_players.entering_Player</code>.
     */
    public void setEnteringPlayer(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>fwdb_test.event_switch_players.entering_Player</code>.
     */
    public String getEnteringPlayer() {
        return (String) get(3);
    }

    /**
     * Setter for <code>fwdb_test.event_switch_players.exiting_Player</code>.
     */
    public void setExitingPlayer(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>fwdb_test.event_switch_players.exiting_Player</code>.
     */
    public String getExitingPlayer() {
        return (String) get(4);
    }

    /**
     * Setter for <code>fwdb_test.event_switch_players.minute</code>.
     */
    public void setMinute(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>fwdb_test.event_switch_players.minute</code>.
     */
    public Integer getMinute() {
        return (Integer) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<Integer, Integer, String, String, String, Integer> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<Integer, Integer, String, String, String, Integer> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return EventSwitchPlayers.EVENT_SWITCH_PLAYERS.EVENT_ID;
    }

    @Override
    public Field<Integer> field2() {
        return EventSwitchPlayers.EVENT_SWITCH_PLAYERS.GAME_ID;
    }

    @Override
    public Field<String> field3() {
        return EventSwitchPlayers.EVENT_SWITCH_PLAYERS.TEAM_NAME;
    }

    @Override
    public Field<String> field4() {
        return EventSwitchPlayers.EVENT_SWITCH_PLAYERS.ENTERING_PLAYER;
    }

    @Override
    public Field<String> field5() {
        return EventSwitchPlayers.EVENT_SWITCH_PLAYERS.EXITING_PLAYER;
    }

    @Override
    public Field<Integer> field6() {
        return EventSwitchPlayers.EVENT_SWITCH_PLAYERS.MINUTE;
    }

    @Override
    public Integer component1() {
        return getEventId();
    }

    @Override
    public Integer component2() {
        return getGameId();
    }

    @Override
    public String component3() {
        return getTeamName();
    }

    @Override
    public String component4() {
        return getEnteringPlayer();
    }

    @Override
    public String component5() {
        return getExitingPlayer();
    }

    @Override
    public Integer component6() {
        return getMinute();
    }

    @Override
    public Integer value1() {
        return getEventId();
    }

    @Override
    public Integer value2() {
        return getGameId();
    }

    @Override
    public String value3() {
        return getTeamName();
    }

    @Override
    public String value4() {
        return getEnteringPlayer();
    }

    @Override
    public String value5() {
        return getExitingPlayer();
    }

    @Override
    public Integer value6() {
        return getMinute();
    }

    @Override
    public EventSwitchPlayersRecord value1(Integer value) {
        setEventId(value);
        return this;
    }

    @Override
    public EventSwitchPlayersRecord value2(Integer value) {
        setGameId(value);
        return this;
    }

    @Override
    public EventSwitchPlayersRecord value3(String value) {
        setTeamName(value);
        return this;
    }

    @Override
    public EventSwitchPlayersRecord value4(String value) {
        setEnteringPlayer(value);
        return this;
    }

    @Override
    public EventSwitchPlayersRecord value5(String value) {
        setExitingPlayer(value);
        return this;
    }

    @Override
    public EventSwitchPlayersRecord value6(Integer value) {
        setMinute(value);
        return this;
    }

    @Override
    public EventSwitchPlayersRecord values(Integer value1, Integer value2, String value3, String value4, String value5, Integer value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached EventSwitchPlayersRecord
     */
    public EventSwitchPlayersRecord() {
        super(EventSwitchPlayers.EVENT_SWITCH_PLAYERS);
    }

    /**
     * Create a detached, initialised EventSwitchPlayersRecord
     */
    public EventSwitchPlayersRecord(Integer eventId, Integer gameId, String teamName, String enteringPlayer, String exitingPlayer, Integer minute) {
        super(EventSwitchPlayers.EVENT_SWITCH_PLAYERS);

        set(0, eventId);
        set(1, gameId);
        set(2, teamName);
        set(3, enteringPlayer);
        set(4, exitingPlayer);
        set(5, minute);
    }
}
