/*
 * This file is generated by jOOQ.
 */
package DB.Tables_Test.tables.records;


import DB.Tables_Test.tables.GamesInSeason;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GamesInSeasonRecord extends UpdatableRecordImpl<GamesInSeasonRecord> implements Record2<Integer, Integer> {

    private static final long serialVersionUID = 1718635889;

    /**
     * Setter for <code>fwdb_test.games_in_season.season_id</code>.
     */
    public void setSeasonId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>fwdb_test.games_in_season.season_id</code>.
     */
    public Integer getSeasonId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>fwdb_test.games_in_season.game_id</code>.
     */
    public void setGameId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>fwdb_test.games_in_season.game_id</code>.
     */
    public Integer getGameId() {
        return (Integer) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<Integer, Integer> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, Integer> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Integer, Integer> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return GamesInSeason.GAMES_IN_SEASON.SEASON_ID;
    }

    @Override
    public Field<Integer> field2() {
        return GamesInSeason.GAMES_IN_SEASON.GAME_ID;
    }

    @Override
    public Integer component1() {
        return getSeasonId();
    }

    @Override
    public Integer component2() {
        return getGameId();
    }

    @Override
    public Integer value1() {
        return getSeasonId();
    }

    @Override
    public Integer value2() {
        return getGameId();
    }

    @Override
    public GamesInSeasonRecord value1(Integer value) {
        setSeasonId(value);
        return this;
    }

    @Override
    public GamesInSeasonRecord value2(Integer value) {
        setGameId(value);
        return this;
    }

    @Override
    public GamesInSeasonRecord values(Integer value1, Integer value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GamesInSeasonRecord
     */
    public GamesInSeasonRecord() {
        super(GamesInSeason.GAMES_IN_SEASON);
    }

    /**
     * Create a detached, initialised GamesInSeasonRecord
     */
    public GamesInSeasonRecord(Integer seasonId, Integer gameId) {
        super(GamesInSeason.GAMES_IN_SEASON);

        set(0, seasonId);
        set(1, gameId);
    }
}
