/*
 * This file is generated by jOOQ.
 */
package DB.Tables_Test.tables.records;


import DB.Tables_Test.enums.PlayerInTeamFieldJob;
import DB.Tables_Test.tables.PlayerInTeam;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PlayerInTeamRecord extends UpdatableRecordImpl<PlayerInTeamRecord> implements Record3<String, String, PlayerInTeamFieldJob> {

    private static final long serialVersionUID = -765646455;

    /**
     * Setter for <code>fwdb_test.player_in_team.username</code>.
     */
    public void setUsername(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>fwdb_test.player_in_team.username</code>.
     */
    public String getUsername() {
        return (String) get(0);
    }

    /**
     * Setter for <code>fwdb_test.player_in_team.team_name</code>.
     */
    public void setTeamName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>fwdb_test.player_in_team.team_name</code>.
     */
    public String getTeamName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>fwdb_test.player_in_team.field_job</code>.
     */
    public void setFieldJob(PlayerInTeamFieldJob value) {
        set(2, value);
    }

    /**
     * Getter for <code>fwdb_test.player_in_team.field_job</code>.
     */
    public PlayerInTeamFieldJob getFieldJob() {
        return (PlayerInTeamFieldJob) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<String, String> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<String, String, PlayerInTeamFieldJob> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<String, String, PlayerInTeamFieldJob> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return PlayerInTeam.PLAYER_IN_TEAM.USERNAME;
    }

    @Override
    public Field<String> field2() {
        return PlayerInTeam.PLAYER_IN_TEAM.TEAM_NAME;
    }

    @Override
    public Field<PlayerInTeamFieldJob> field3() {
        return PlayerInTeam.PLAYER_IN_TEAM.FIELD_JOB;
    }

    @Override
    public String component1() {
        return getUsername();
    }

    @Override
    public String component2() {
        return getTeamName();
    }

    @Override
    public PlayerInTeamFieldJob component3() {
        return getFieldJob();
    }

    @Override
    public String value1() {
        return getUsername();
    }

    @Override
    public String value2() {
        return getTeamName();
    }

    @Override
    public PlayerInTeamFieldJob value3() {
        return getFieldJob();
    }

    @Override
    public PlayerInTeamRecord value1(String value) {
        setUsername(value);
        return this;
    }

    @Override
    public PlayerInTeamRecord value2(String value) {
        setTeamName(value);
        return this;
    }

    @Override
    public PlayerInTeamRecord value3(PlayerInTeamFieldJob value) {
        setFieldJob(value);
        return this;
    }

    @Override
    public PlayerInTeamRecord values(String value1, String value2, PlayerInTeamFieldJob value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PlayerInTeamRecord
     */
    public PlayerInTeamRecord() {
        super(PlayerInTeam.PLAYER_IN_TEAM);
    }

    /**
     * Create a detached, initialised PlayerInTeamRecord
     */
    public PlayerInTeamRecord(String username, String teamName, PlayerInTeamFieldJob fieldJob) {
        super(PlayerInTeam.PLAYER_IN_TEAM);

        set(0, username);
        set(1, teamName);
        set(2, fieldJob);
    }
}
