/*
 * This file is generated by jOOQ.
 */
package DB.Tables_Test.tables.records;


import DB.Tables_Test.tables.RefereeInSeason;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RefereeInSeasonRecord extends UpdatableRecordImpl<RefereeInSeasonRecord> implements Record2<String, Integer> {

    private static final long serialVersionUID = -2137465273;

    /**
     * Setter for <code>fwdb_test.referee_in_season.username</code>.
     */
    public void setUsername(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>fwdb_test.referee_in_season.username</code>.
     */
    public String getUsername() {
        return (String) get(0);
    }

    /**
     * Setter for <code>fwdb_test.referee_in_season.season_id</code>.
     */
    public void setSeasonId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>fwdb_test.referee_in_season.season_id</code>.
     */
    public Integer getSeasonId() {
        return (Integer) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<String, Integer> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<String, Integer> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<String, Integer> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return RefereeInSeason.REFEREE_IN_SEASON.USERNAME;
    }

    @Override
    public Field<Integer> field2() {
        return RefereeInSeason.REFEREE_IN_SEASON.SEASON_ID;
    }

    @Override
    public String component1() {
        return getUsername();
    }

    @Override
    public Integer component2() {
        return getSeasonId();
    }

    @Override
    public String value1() {
        return getUsername();
    }

    @Override
    public Integer value2() {
        return getSeasonId();
    }

    @Override
    public RefereeInSeasonRecord value1(String value) {
        setUsername(value);
        return this;
    }

    @Override
    public RefereeInSeasonRecord value2(Integer value) {
        setSeasonId(value);
        return this;
    }

    @Override
    public RefereeInSeasonRecord values(String value1, Integer value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RefereeInSeasonRecord
     */
    public RefereeInSeasonRecord() {
        super(RefereeInSeason.REFEREE_IN_SEASON);
    }

    /**
     * Create a detached, initialised RefereeInSeasonRecord
     */
    public RefereeInSeasonRecord(String username, Integer seasonId) {
        super(RefereeInSeason.REFEREE_IN_SEASON);

        set(0, username);
        set(1, seasonId);
    }
}
