/*
 * This file is generated by jOOQ.
 */
package DB.Tables_Test.tables.records;


import DB.Tables_Test.tables.Systemuser;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SystemuserRecord extends UpdatableRecordImpl<SystemuserRecord> implements Record5<String, String, String, String, Boolean> {

    private static final long serialVersionUID = -2065941680;

    /**
     * Setter for <code>fwdb_test.systemuser.username</code>.
     */
    public void setUsername(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>fwdb_test.systemuser.username</code>.
     */
    public String getUsername() {
        return (String) get(0);
    }

    /**
     * Setter for <code>fwdb_test.systemuser.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>fwdb_test.systemuser.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>fwdb_test.systemuser.password</code>.
     */
    public void setPassword(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>fwdb_test.systemuser.password</code>.
     */
    public String getPassword() {
        return (String) get(2);
    }

    /**
     * Setter for <code>fwdb_test.systemuser.email</code>.
     */
    public void setEmail(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>fwdb_test.systemuser.email</code>.
     */
    public String getEmail() {
        return (String) get(3);
    }

    /**
     * Setter for <code>fwdb_test.systemuser.notify_by_email</code>.
     */
    public void setNotifyByEmail(Boolean value) {
        set(4, value);
    }

    /**
     * Getter for <code>fwdb_test.systemuser.notify_by_email</code>.
     */
    public Boolean getNotifyByEmail() {
        return (Boolean) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<String, String, String, String, Boolean> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<String, String, String, String, Boolean> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return Systemuser.SYSTEMUSER.USERNAME;
    }

    @Override
    public Field<String> field2() {
        return Systemuser.SYSTEMUSER.NAME;
    }

    @Override
    public Field<String> field3() {
        return Systemuser.SYSTEMUSER.PASSWORD;
    }

    @Override
    public Field<String> field4() {
        return Systemuser.SYSTEMUSER.EMAIL;
    }

    @Override
    public Field<Boolean> field5() {
        return Systemuser.SYSTEMUSER.NOTIFY_BY_EMAIL;
    }

    @Override
    public String component1() {
        return getUsername();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public String component3() {
        return getPassword();
    }

    @Override
    public String component4() {
        return getEmail();
    }

    @Override
    public Boolean component5() {
        return getNotifyByEmail();
    }

    @Override
    public String value1() {
        return getUsername();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public String value3() {
        return getPassword();
    }

    @Override
    public String value4() {
        return getEmail();
    }

    @Override
    public Boolean value5() {
        return getNotifyByEmail();
    }

    @Override
    public SystemuserRecord value1(String value) {
        setUsername(value);
        return this;
    }

    @Override
    public SystemuserRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public SystemuserRecord value3(String value) {
        setPassword(value);
        return this;
    }

    @Override
    public SystemuserRecord value4(String value) {
        setEmail(value);
        return this;
    }

    @Override
    public SystemuserRecord value5(Boolean value) {
        setNotifyByEmail(value);
        return this;
    }

    @Override
    public SystemuserRecord values(String value1, String value2, String value3, String value4, Boolean value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SystemuserRecord
     */
    public SystemuserRecord() {
        super(Systemuser.SYSTEMUSER);
    }

    /**
     * Create a detached, initialised SystemuserRecord
     */
    public SystemuserRecord(String username, String name, String password, String email, Boolean notifyByEmail) {
        super(Systemuser.SYSTEMUSER);

        set(0, username);
        set(1, name);
        set(2, password);
        set(3, email);
        set(4, notifyByEmail);
    }
}
