/*
 * This file is generated by jOOQ.
 */
package DB.Tables_Test.tables.records;


import DB.Tables_Test.tables.TeamOwner;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Row1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TeamOwnerRecord extends UpdatableRecordImpl<TeamOwnerRecord> implements Record1<String> {

    private static final long serialVersionUID = -2131667850;

    /**
     * Setter for <code>fwdb_test.team_owner.username</code>.
     */
    public void setUsername(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>fwdb_test.team_owner.username</code>.
     */
    public String getUsername() {
        return (String) get(0);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record1 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row1<String> fieldsRow() {
        return (Row1) super.fieldsRow();
    }

    @Override
    public Row1<String> valuesRow() {
        return (Row1) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return TeamOwner.TEAM_OWNER.USERNAME;
    }

    @Override
    public String component1() {
        return getUsername();
    }

    @Override
    public String value1() {
        return getUsername();
    }

    @Override
    public TeamOwnerRecord value1(String value) {
        setUsername(value);
        return this;
    }

    @Override
    public TeamOwnerRecord values(String value1) {
        value1(value1);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TeamOwnerRecord
     */
    public TeamOwnerRecord() {
        super(TeamOwner.TEAM_OWNER);
    }

    /**
     * Create a detached, initialised TeamOwnerRecord
     */
    public TeamOwnerRecord(String username) {
        super(TeamOwner.TEAM_OWNER);

        set(0, username);
    }
}
