/*
 * This file is generated by jOOQ.
 */
package DB.Tables.tables.records;


import DB.Tables.tables.EventLog;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EventLogRecord extends UpdatableRecordImpl<EventLogRecord> implements Record7<Integer, LocalDateTime, String, String, String, String, String> {

    private static final long serialVersionUID = 1403109988;

    /**
     * Setter for <code>fwdb.event_log.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>fwdb.event_log.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>fwdb.event_log.date</code>.
     */
    public void setDate(LocalDateTime value) {
        set(1, value);
    }

    /**
     * Getter for <code>fwdb.event_log.date</code>.
     */
    public LocalDateTime getDate() {
        return (LocalDateTime) get(1);
    }

    /**
     * Setter for <code>fwdb.event_log.class</code>.
     */
    public void setClass_(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>fwdb.event_log.class</code>.
     */
    public String getClass_() {
        return (String) get(2);
    }

    /**
     * Setter for <code>fwdb.event_log.level</code>.
     */
    public void setLevel(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>fwdb.event_log.level</code>.
     */
    public String getLevel() {
        return (String) get(3);
    }

    /**
     * Setter for <code>fwdb.event_log.username</code>.
     */
    public void setUsername(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>fwdb.event_log.username</code>.
     */
    public String getUsername() {
        return (String) get(4);
    }

    /**
     * Setter for <code>fwdb.event_log.action</code>.
     */
    public void setAction(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>fwdb.event_log.action</code>.
     */
    public String getAction() {
        return (String) get(5);
    }

    /**
     * Setter for <code>fwdb.event_log.message</code>.
     */
    public void setMessage(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>fwdb.event_log.message</code>.
     */
    public String getMessage() {
        return (String) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row7<Integer, LocalDateTime, String, String, String, String, String> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    @Override
    public Row7<Integer, LocalDateTime, String, String, String, String, String> valuesRow() {
        return (Row7) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return EventLog.EVENT_LOG.ID;
    }

    @Override
    public Field<LocalDateTime> field2() {
        return EventLog.EVENT_LOG.DATE;
    }

    @Override
    public Field<String> field3() {
        return EventLog.EVENT_LOG.CLASS;
    }

    @Override
    public Field<String> field4() {
        return EventLog.EVENT_LOG.LEVEL;
    }

    @Override
    public Field<String> field5() {
        return EventLog.EVENT_LOG.USERNAME;
    }

    @Override
    public Field<String> field6() {
        return EventLog.EVENT_LOG.ACTION;
    }

    @Override
    public Field<String> field7() {
        return EventLog.EVENT_LOG.MESSAGE;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public LocalDateTime component2() {
        return getDate();
    }

    @Override
    public String component3() {
        return getClass_();
    }

    @Override
    public String component4() {
        return getLevel();
    }

    @Override
    public String component5() {
        return getUsername();
    }

    @Override
    public String component6() {
        return getAction();
    }

    @Override
    public String component7() {
        return getMessage();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public LocalDateTime value2() {
        return getDate();
    }

    @Override
    public String value3() {
        return getClass_();
    }

    @Override
    public String value4() {
        return getLevel();
    }

    @Override
    public String value5() {
        return getUsername();
    }

    @Override
    public String value6() {
        return getAction();
    }

    @Override
    public String value7() {
        return getMessage();
    }

    @Override
    public EventLogRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public EventLogRecord value2(LocalDateTime value) {
        setDate(value);
        return this;
    }

    @Override
    public EventLogRecord value3(String value) {
        setClass_(value);
        return this;
    }

    @Override
    public EventLogRecord value4(String value) {
        setLevel(value);
        return this;
    }

    @Override
    public EventLogRecord value5(String value) {
        setUsername(value);
        return this;
    }

    @Override
    public EventLogRecord value6(String value) {
        setAction(value);
        return this;
    }

    @Override
    public EventLogRecord value7(String value) {
        setMessage(value);
        return this;
    }

    @Override
    public EventLogRecord values(Integer value1, LocalDateTime value2, String value3, String value4, String value5, String value6, String value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached EventLogRecord
     */
    public EventLogRecord() {
        super(EventLog.EVENT_LOG);
    }

    /**
     * Create a detached, initialised EventLogRecord
     */
    public EventLogRecord(Integer id, LocalDateTime date, String class_, String level, String username, String action, String message) {
        super(EventLog.EVENT_LOG);

        set(0, id);
        set(1, date);
        set(2, class_);
        set(3, level);
        set(4, username);
        set(5, action);
        set(6, message);
    }
}
