/*
 * This file is generated by jOOQ.
 */
package DB.Tables.tables.records;


import DB.Tables.enums.EventCardType;
import DB.Tables.tables.EventCard;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EventCardRecord extends UpdatableRecordImpl<EventCardRecord> implements Record5<Integer, Integer, String, EventCardType, Integer> {

    private static final long serialVersionUID = 1824531100;

    /**
     * Setter for <code>fwdb.event_card.event_id</code>.
     */
    public void setEventId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>fwdb.event_card.event_id</code>.
     */
    public Integer getEventId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>fwdb.event_card.game_id</code>.
     */
    public void setGameId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>fwdb.event_card.game_id</code>.
     */
    public Integer getGameId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>fwdb.event_card.offender_name</code>.
     */
    public void setOffenderName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>fwdb.event_card.offender_name</code>.
     */
    public String getOffenderName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>fwdb.event_card.type</code>.
     */
    public void setType(EventCardType value) {
        set(3, value);
    }

    /**
     * Getter for <code>fwdb.event_card.type</code>.
     */
    public EventCardType getType() {
        return (EventCardType) get(3);
    }

    /**
     * Setter for <code>fwdb.event_card.minute</code>.
     */
    public void setMinute(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>fwdb.event_card.minute</code>.
     */
    public Integer getMinute() {
        return (Integer) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Integer, Integer, String, EventCardType, Integer> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Integer, Integer, String, EventCardType, Integer> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return EventCard.EVENT_CARD.EVENT_ID;
    }

    @Override
    public Field<Integer> field2() {
        return EventCard.EVENT_CARD.GAME_ID;
    }

    @Override
    public Field<String> field3() {
        return EventCard.EVENT_CARD.OFFENDER_NAME;
    }

    @Override
    public Field<EventCardType> field4() {
        return EventCard.EVENT_CARD.TYPE;
    }

    @Override
    public Field<Integer> field5() {
        return EventCard.EVENT_CARD.MINUTE;
    }

    @Override
    public Integer component1() {
        return getEventId();
    }

    @Override
    public Integer component2() {
        return getGameId();
    }

    @Override
    public String component3() {
        return getOffenderName();
    }

    @Override
    public EventCardType component4() {
        return getType();
    }

    @Override
    public Integer component5() {
        return getMinute();
    }

    @Override
    public Integer value1() {
        return getEventId();
    }

    @Override
    public Integer value2() {
        return getGameId();
    }

    @Override
    public String value3() {
        return getOffenderName();
    }

    @Override
    public EventCardType value4() {
        return getType();
    }

    @Override
    public Integer value5() {
        return getMinute();
    }

    @Override
    public EventCardRecord value1(Integer value) {
        setEventId(value);
        return this;
    }

    @Override
    public EventCardRecord value2(Integer value) {
        setGameId(value);
        return this;
    }

    @Override
    public EventCardRecord value3(String value) {
        setOffenderName(value);
        return this;
    }

    @Override
    public EventCardRecord value4(EventCardType value) {
        setType(value);
        return this;
    }

    @Override
    public EventCardRecord value5(Integer value) {
        setMinute(value);
        return this;
    }

    @Override
    public EventCardRecord values(Integer value1, Integer value2, String value3, EventCardType value4, Integer value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached EventCardRecord
     */
    public EventCardRecord() {
        super(EventCard.EVENT_CARD);
    }

    /**
     * Create a detached, initialised EventCardRecord
     */
    public EventCardRecord(Integer eventId, Integer gameId, String offenderName, EventCardType type, Integer minute) {
        super(EventCard.EVENT_CARD);

        set(0, eventId);
        set(1, gameId);
        set(2, offenderName);
        set(3, type);
        set(4, minute);
    }
}
