/*
 * This file is generated by jOOQ.
 */
package DB.Tables.tables.records;


import DB.Tables.tables.EventGoal;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EventGoalRecord extends UpdatableRecordImpl<EventGoalRecord> implements Record6<Integer, Integer, String, String, String, Integer> {

    private static final long serialVersionUID = -2068892300;

    /**
     * Setter for <code>fwdb.event_goal.event_id</code>.
     */
    public void setEventId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>fwdb.event_goal.event_id</code>.
     */
    public Integer getEventId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>fwdb.event_goal.game_id</code>.
     */
    public void setGameId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>fwdb.event_goal.game_id</code>.
     */
    public Integer getGameId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>fwdb.event_goal.scored_team</code>.
     */
    public void setScoredTeam(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>fwdb.event_goal.scored_team</code>.
     */
    public String getScoredTeam() {
        return (String) get(2);
    }

    /**
     * Setter for <code>fwdb.event_goal.scored_on_team</code>.
     */
    public void setScoredOnTeam(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>fwdb.event_goal.scored_on_team</code>.
     */
    public String getScoredOnTeam() {
        return (String) get(3);
    }

    /**
     * Setter for <code>fwdb.event_goal.scorer_name</code>.
     */
    public void setScorerName(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>fwdb.event_goal.scorer_name</code>.
     */
    public String getScorerName() {
        return (String) get(4);
    }

    /**
     * Setter for <code>fwdb.event_goal.minute</code>.
     */
    public void setMinute(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>fwdb.event_goal.minute</code>.
     */
    public Integer getMinute() {
        return (Integer) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<Integer, Integer, String, String, String, Integer> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<Integer, Integer, String, String, String, Integer> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return EventGoal.EVENT_GOAL.EVENT_ID;
    }

    @Override
    public Field<Integer> field2() {
        return EventGoal.EVENT_GOAL.GAME_ID;
    }

    @Override
    public Field<String> field3() {
        return EventGoal.EVENT_GOAL.SCORED_TEAM;
    }

    @Override
    public Field<String> field4() {
        return EventGoal.EVENT_GOAL.SCORED_ON_TEAM;
    }

    @Override
    public Field<String> field5() {
        return EventGoal.EVENT_GOAL.SCORER_NAME;
    }

    @Override
    public Field<Integer> field6() {
        return EventGoal.EVENT_GOAL.MINUTE;
    }

    @Override
    public Integer component1() {
        return getEventId();
    }

    @Override
    public Integer component2() {
        return getGameId();
    }

    @Override
    public String component3() {
        return getScoredTeam();
    }

    @Override
    public String component4() {
        return getScoredOnTeam();
    }

    @Override
    public String component5() {
        return getScorerName();
    }

    @Override
    public Integer component6() {
        return getMinute();
    }

    @Override
    public Integer value1() {
        return getEventId();
    }

    @Override
    public Integer value2() {
        return getGameId();
    }

    @Override
    public String value3() {
        return getScoredTeam();
    }

    @Override
    public String value4() {
        return getScoredOnTeam();
    }

    @Override
    public String value5() {
        return getScorerName();
    }

    @Override
    public Integer value6() {
        return getMinute();
    }

    @Override
    public EventGoalRecord value1(Integer value) {
        setEventId(value);
        return this;
    }

    @Override
    public EventGoalRecord value2(Integer value) {
        setGameId(value);
        return this;
    }

    @Override
    public EventGoalRecord value3(String value) {
        setScoredTeam(value);
        return this;
    }

    @Override
    public EventGoalRecord value4(String value) {
        setScoredOnTeam(value);
        return this;
    }

    @Override
    public EventGoalRecord value5(String value) {
        setScorerName(value);
        return this;
    }

    @Override
    public EventGoalRecord value6(Integer value) {
        setMinute(value);
        return this;
    }

    @Override
    public EventGoalRecord values(Integer value1, Integer value2, String value3, String value4, String value5, Integer value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached EventGoalRecord
     */
    public EventGoalRecord() {
        super(EventGoal.EVENT_GOAL);
    }

    /**
     * Create a detached, initialised EventGoalRecord
     */
    public EventGoalRecord(Integer eventId, Integer gameId, String scoredTeam, String scoredOnTeam, String scorerName, Integer minute) {
        super(EventGoal.EVENT_GOAL);

        set(0, eventId);
        set(1, gameId);
        set(2, scoredTeam);
        set(3, scoredOnTeam);
        set(4, scorerName);
        set(5, minute);
    }
}
