/*
 * This file is generated by jOOQ.
 */
package DB.Tables.tables.records;


import DB.Tables.enums.ManagerInTeamsAddCoach;
import DB.Tables.enums.ManagerInTeamsAddPlayer;
import DB.Tables.enums.ManagerInTeamsChangePositionPlayer;
import DB.Tables.enums.ManagerInTeamsChangeTeamJobCoach;
import DB.Tables.enums.ManagerInTeamsRemoveCoach;
import DB.Tables.enums.ManagerInTeamsRemovePlayer;
import DB.Tables.tables.ManagerInTeams;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ManagerInTeamsRecord extends UpdatableRecordImpl<ManagerInTeamsRecord> implements Record8<String, String, ManagerInTeamsRemovePlayer, ManagerInTeamsAddPlayer, ManagerInTeamsChangePositionPlayer, ManagerInTeamsRemoveCoach, ManagerInTeamsAddCoach, ManagerInTeamsChangeTeamJobCoach> {

    private static final long serialVersionUID = 1182963893;

    /**
     * Setter for <code>fwdb.manager_in_teams.username</code>.
     */
    public void setUsername(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>fwdb.manager_in_teams.username</code>.
     */
    public String getUsername() {
        return (String) get(0);
    }

    /**
     * Setter for <code>fwdb.manager_in_teams.team_name</code>.
     */
    public void setTeamName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>fwdb.manager_in_teams.team_name</code>.
     */
    public String getTeamName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>fwdb.manager_in_teams.REMOVE_PLAYER</code>.
     */
    public void setRemovePlayer(ManagerInTeamsRemovePlayer value) {
        set(2, value);
    }

    /**
     * Getter for <code>fwdb.manager_in_teams.REMOVE_PLAYER</code>.
     */
    public ManagerInTeamsRemovePlayer getRemovePlayer() {
        return (ManagerInTeamsRemovePlayer) get(2);
    }

    /**
     * Setter for <code>fwdb.manager_in_teams.ADD_PLAYER</code>.
     */
    public void setAddPlayer(ManagerInTeamsAddPlayer value) {
        set(3, value);
    }

    /**
     * Getter for <code>fwdb.manager_in_teams.ADD_PLAYER</code>.
     */
    public ManagerInTeamsAddPlayer getAddPlayer() {
        return (ManagerInTeamsAddPlayer) get(3);
    }

    /**
     * Setter for <code>fwdb.manager_in_teams.CHANGE_POSITION_PLAYER</code>.
     */
    public void setChangePositionPlayer(ManagerInTeamsChangePositionPlayer value) {
        set(4, value);
    }

    /**
     * Getter for <code>fwdb.manager_in_teams.CHANGE_POSITION_PLAYER</code>.
     */
    public ManagerInTeamsChangePositionPlayer getChangePositionPlayer() {
        return (ManagerInTeamsChangePositionPlayer) get(4);
    }

    /**
     * Setter for <code>fwdb.manager_in_teams.REMOVE_COACH</code>.
     */
    public void setRemoveCoach(ManagerInTeamsRemoveCoach value) {
        set(5, value);
    }

    /**
     * Getter for <code>fwdb.manager_in_teams.REMOVE_COACH</code>.
     */
    public ManagerInTeamsRemoveCoach getRemoveCoach() {
        return (ManagerInTeamsRemoveCoach) get(5);
    }

    /**
     * Setter for <code>fwdb.manager_in_teams.ADD_COACH</code>.
     */
    public void setAddCoach(ManagerInTeamsAddCoach value) {
        set(6, value);
    }

    /**
     * Getter for <code>fwdb.manager_in_teams.ADD_COACH</code>.
     */
    public ManagerInTeamsAddCoach getAddCoach() {
        return (ManagerInTeamsAddCoach) get(6);
    }

    /**
     * Setter for <code>fwdb.manager_in_teams.CHANGE_TEAM_JOB_COACH</code>.
     */
    public void setChangeTeamJobCoach(ManagerInTeamsChangeTeamJobCoach value) {
        set(7, value);
    }

    /**
     * Getter for <code>fwdb.manager_in_teams.CHANGE_TEAM_JOB_COACH</code>.
     */
    public ManagerInTeamsChangeTeamJobCoach getChangeTeamJobCoach() {
        return (ManagerInTeamsChangeTeamJobCoach) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<String, String> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row8<String, String, ManagerInTeamsRemovePlayer, ManagerInTeamsAddPlayer, ManagerInTeamsChangePositionPlayer, ManagerInTeamsRemoveCoach, ManagerInTeamsAddCoach, ManagerInTeamsChangeTeamJobCoach> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    @Override
    public Row8<String, String, ManagerInTeamsRemovePlayer, ManagerInTeamsAddPlayer, ManagerInTeamsChangePositionPlayer, ManagerInTeamsRemoveCoach, ManagerInTeamsAddCoach, ManagerInTeamsChangeTeamJobCoach> valuesRow() {
        return (Row8) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return ManagerInTeams.MANAGER_IN_TEAMS.USERNAME;
    }

    @Override
    public Field<String> field2() {
        return ManagerInTeams.MANAGER_IN_TEAMS.TEAM_NAME;
    }

    @Override
    public Field<ManagerInTeamsRemovePlayer> field3() {
        return ManagerInTeams.MANAGER_IN_TEAMS.REMOVE_PLAYER;
    }

    @Override
    public Field<ManagerInTeamsAddPlayer> field4() {
        return ManagerInTeams.MANAGER_IN_TEAMS.ADD_PLAYER;
    }

    @Override
    public Field<ManagerInTeamsChangePositionPlayer> field5() {
        return ManagerInTeams.MANAGER_IN_TEAMS.CHANGE_POSITION_PLAYER;
    }

    @Override
    public Field<ManagerInTeamsRemoveCoach> field6() {
        return ManagerInTeams.MANAGER_IN_TEAMS.REMOVE_COACH;
    }

    @Override
    public Field<ManagerInTeamsAddCoach> field7() {
        return ManagerInTeams.MANAGER_IN_TEAMS.ADD_COACH;
    }

    @Override
    public Field<ManagerInTeamsChangeTeamJobCoach> field8() {
        return ManagerInTeams.MANAGER_IN_TEAMS.CHANGE_TEAM_JOB_COACH;
    }

    @Override
    public String component1() {
        return getUsername();
    }

    @Override
    public String component2() {
        return getTeamName();
    }

    @Override
    public ManagerInTeamsRemovePlayer component3() {
        return getRemovePlayer();
    }

    @Override
    public ManagerInTeamsAddPlayer component4() {
        return getAddPlayer();
    }

    @Override
    public ManagerInTeamsChangePositionPlayer component5() {
        return getChangePositionPlayer();
    }

    @Override
    public ManagerInTeamsRemoveCoach component6() {
        return getRemoveCoach();
    }

    @Override
    public ManagerInTeamsAddCoach component7() {
        return getAddCoach();
    }

    @Override
    public ManagerInTeamsChangeTeamJobCoach component8() {
        return getChangeTeamJobCoach();
    }

    @Override
    public String value1() {
        return getUsername();
    }

    @Override
    public String value2() {
        return getTeamName();
    }

    @Override
    public ManagerInTeamsRemovePlayer value3() {
        return getRemovePlayer();
    }

    @Override
    public ManagerInTeamsAddPlayer value4() {
        return getAddPlayer();
    }

    @Override
    public ManagerInTeamsChangePositionPlayer value5() {
        return getChangePositionPlayer();
    }

    @Override
    public ManagerInTeamsRemoveCoach value6() {
        return getRemoveCoach();
    }

    @Override
    public ManagerInTeamsAddCoach value7() {
        return getAddCoach();
    }

    @Override
    public ManagerInTeamsChangeTeamJobCoach value8() {
        return getChangeTeamJobCoach();
    }

    @Override
    public ManagerInTeamsRecord value1(String value) {
        setUsername(value);
        return this;
    }

    @Override
    public ManagerInTeamsRecord value2(String value) {
        setTeamName(value);
        return this;
    }

    @Override
    public ManagerInTeamsRecord value3(ManagerInTeamsRemovePlayer value) {
        setRemovePlayer(value);
        return this;
    }

    @Override
    public ManagerInTeamsRecord value4(ManagerInTeamsAddPlayer value) {
        setAddPlayer(value);
        return this;
    }

    @Override
    public ManagerInTeamsRecord value5(ManagerInTeamsChangePositionPlayer value) {
        setChangePositionPlayer(value);
        return this;
    }

    @Override
    public ManagerInTeamsRecord value6(ManagerInTeamsRemoveCoach value) {
        setRemoveCoach(value);
        return this;
    }

    @Override
    public ManagerInTeamsRecord value7(ManagerInTeamsAddCoach value) {
        setAddCoach(value);
        return this;
    }

    @Override
    public ManagerInTeamsRecord value8(ManagerInTeamsChangeTeamJobCoach value) {
        setChangeTeamJobCoach(value);
        return this;
    }

    @Override
    public ManagerInTeamsRecord values(String value1, String value2, ManagerInTeamsRemovePlayer value3, ManagerInTeamsAddPlayer value4, ManagerInTeamsChangePositionPlayer value5, ManagerInTeamsRemoveCoach value6, ManagerInTeamsAddCoach value7, ManagerInTeamsChangeTeamJobCoach value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ManagerInTeamsRecord
     */
    public ManagerInTeamsRecord() {
        super(ManagerInTeams.MANAGER_IN_TEAMS);
    }

    /**
     * Create a detached, initialised ManagerInTeamsRecord
     */
    public ManagerInTeamsRecord(String username, String teamName, ManagerInTeamsRemovePlayer removePlayer, ManagerInTeamsAddPlayer addPlayer, ManagerInTeamsChangePositionPlayer changePositionPlayer, ManagerInTeamsRemoveCoach removeCoach, ManagerInTeamsAddCoach addCoach, ManagerInTeamsChangeTeamJobCoach changeTeamJobCoach) {
        super(ManagerInTeams.MANAGER_IN_TEAMS);

        set(0, username);
        set(1, teamName);
        set(2, removePlayer);
        set(3, addPlayer);
        set(4, changePositionPlayer);
        set(5, removeCoach);
        set(6, addCoach);
        set(7, changeTeamJobCoach);
    }
}
