/*
 * This file is generated by jOOQ.
 */
package DB.Tables.tables.records;


import DB.Tables.tables.StadiumHomeTeams;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StadiumHomeTeamsRecord extends UpdatableRecordImpl<StadiumHomeTeamsRecord> implements Record2<Integer, String> {

    private static final long serialVersionUID = 408748448;

    /**
     * Setter for <code>fwdb.stadium_home_teams.stadium_id</code>.
     */
    public void setStadiumId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>fwdb.stadium_home_teams.stadium_id</code>.
     */
    public Integer getStadiumId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>fwdb.stadium_home_teams.team_name</code>.
     */
    public void setTeamName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>fwdb.stadium_home_teams.team_name</code>.
     */
    public String getTeamName() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<Integer, String> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Integer, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return StadiumHomeTeams.STADIUM_HOME_TEAMS.STADIUM_ID;
    }

    @Override
    public Field<String> field2() {
        return StadiumHomeTeams.STADIUM_HOME_TEAMS.TEAM_NAME;
    }

    @Override
    public Integer component1() {
        return getStadiumId();
    }

    @Override
    public String component2() {
        return getTeamName();
    }

    @Override
    public Integer value1() {
        return getStadiumId();
    }

    @Override
    public String value2() {
        return getTeamName();
    }

    @Override
    public StadiumHomeTeamsRecord value1(Integer value) {
        setStadiumId(value);
        return this;
    }

    @Override
    public StadiumHomeTeamsRecord value2(String value) {
        setTeamName(value);
        return this;
    }

    @Override
    public StadiumHomeTeamsRecord values(Integer value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached StadiumHomeTeamsRecord
     */
    public StadiumHomeTeamsRecord() {
        super(StadiumHomeTeams.STADIUM_HOME_TEAMS);
    }

    /**
     * Create a detached, initialised StadiumHomeTeamsRecord
     */
    public StadiumHomeTeamsRecord(Integer stadiumId, String teamName) {
        super(StadiumHomeTeams.STADIUM_HOME_TEAMS);

        set(0, stadiumId);
        set(1, teamName);
    }
}
