/*
 * This file is generated by jOOQ.
 */
package DB.Tables.enums;


import org.jooq.Catalog;
import org.jooq.EnumType;
import org.jooq.Schema;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public enum ManagerInTeamsChangeTeamJobCoach implements EnumType {

    Y("Y"),

    N("N");

    private final String literal;

    private ManagerInTeamsChangeTeamJobCoach(String literal) {
        this.literal = literal;
    }

    @Override
    public Catalog getCatalog() {
        return null;
    }

    @Override
    public Schema getSchema() {
        return null;
    }

    @Override
    public String getName() {
        return "manager_in_teams_CHANGE_TEAM_JOB_COACH";
    }

    @Override
    public String getLiteral() {
        return literal;
    }
}
