/*
 * This file is generated by jOOQ.
 */
package DB.Tables.enums;


import org.jooq.Catalog;
import org.jooq.EnumType;
import org.jooq.Schema;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public enum RefereeTraining implements EnumType {

    MAIN_REFEREE("MAIN_REFEREE"),

    SIDE_REFEREE("SIDE_REFEREE"),

    VAR_REFEREE("VAR_REFEREE");

    private final String literal;

    private RefereeTraining(String literal) {
        this.literal = literal;
    }

    @Override
    public Catalog getCatalog() {
        return null;
    }

    @Override
    public Schema getSchema() {
        return null;
    }

    @Override
    public String getName() {
        return "referee_training";
    }

    @Override
    public String getLiteral() {
        return literal;
    }
}
