/*
 * This file is generated by jOOQ.
 */
package DB.Tables.enums;


import org.jooq.Catalog;
import org.jooq.EnumType;
import org.jooq.Schema;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public enum UserRolesRoleType implements EnumType {

    PLAYER("PLAYER"),

    COACH("COACH"),

    TEAM_MANAGER("TEAM_MANAGER"),

    TEAM_OWNER("TEAM_OWNER"),

    SYSTEM_ADMIN("SYSTEM_ADMIN"),

    REFEREE("REFEREE"),

    ASSOCIATION_REPRESENTATIVE("ASSOCIATION_REPRESENTATIVE");

    private final String literal;

    private UserRolesRoleType(String literal) {
        this.literal = literal;
    }

    @Override
    public Catalog getCatalog() {
        return null;
    }

    @Override
    public Schema getSchema() {
        return null;
    }

    @Override
    public String getName() {
        return "user_roles_role_type";
    }

    @Override
    public String getLiteral() {
        return literal;
    }
}
