# Add 'User-Related' label to any changes within 'Domain.Users' folder or any subfolders
Domain-Related:
  - src/main/java/Domain/**/*

DB-Related:
  - src/main/java/DB/**/*

GUI-Related:
  - src/main/java/GUI/**/*

Service-Related:
  - src/main/java/Service/**/*