/*
 * This file is generated by jOOQ.
 */
package DB.Tables;


import DB.Tables.tables.Tabletest;


/**
 * Convenience access to all tables in testdb
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>testdb.tabletest</code>.
     */
    public static final Tabletest TABLETEST = Tabletest.TABLETEST;
}
