/*
 * This file is generated by jOOQ.
 */
package DB.Tables;


import DB.Tables.tables.Tabletest;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Testdb extends SchemaImpl {

    private static final long serialVersionUID = -656808968;

    /**
     * The reference instance of <code>testdb</code>
     */
    public static final Testdb TESTDB = new Testdb();

    /**
     * The table <code>testdb.tabletest</code>.
     */
    public final Tabletest TABLETEST = Tabletest.TABLETEST;

    /**
     * No further instances allowed
     */
    private Testdb() {
        super("testdb", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            Tabletest.TABLETEST);
    }
}
