/*
 * This file is generated by jOOQ.
 */
package DB.Tables.tables;


import DB.Tables.Fwdb;
import DB.Tables.Keys;
import DB.Tables.tables.records.EventPenaltyRecord;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row4;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EventPenalty extends TableImpl<EventPenaltyRecord> {

    private static final long serialVersionUID = -680747141;

    /**
     * The reference instance of <code>fwdb.event_penalty</code>
     */
    public static final EventPenalty EVENT_PENALTY = new EventPenalty();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<EventPenaltyRecord> getRecordType() {
        return EventPenaltyRecord.class;
    }

    /**
     * The column <code>fwdb.event_penalty.event_id</code>.
     */
    public final TableField<EventPenaltyRecord, Integer> EVENT_ID = createField(DSL.name("event_id"), org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>fwdb.event_penalty.game_id</code>.
     */
    public final TableField<EventPenaltyRecord, Integer> GAME_ID = createField(DSL.name("game_id"), org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>fwdb.event_penalty.team_name</code>.
     */
    public final TableField<EventPenaltyRecord, String> TEAM_NAME = createField(DSL.name("team_name"), org.jooq.impl.SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>fwdb.event_penalty.minute</code>.
     */
    public final TableField<EventPenaltyRecord, Integer> MINUTE = createField(DSL.name("minute"), org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * Create a <code>fwdb.event_penalty</code> table reference
     */
    public EventPenalty() {
        this(DSL.name("event_penalty"), null);
    }

    /**
     * Create an aliased <code>fwdb.event_penalty</code> table reference
     */
    public EventPenalty(String alias) {
        this(DSL.name(alias), EVENT_PENALTY);
    }

    /**
     * Create an aliased <code>fwdb.event_penalty</code> table reference
     */
    public EventPenalty(Name alias) {
        this(alias, EVENT_PENALTY);
    }

    private EventPenalty(Name alias, Table<EventPenaltyRecord> aliased) {
        this(alias, aliased, null);
    }

    private EventPenalty(Name alias, Table<EventPenaltyRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    public <O extends Record> EventPenalty(Table<O> child, ForeignKey<O, EventPenaltyRecord> key) {
        super(child, key, EVENT_PENALTY);
    }

    @Override
    public Schema getSchema() {
        return Fwdb.FWDB;
    }

    @Override
    public Identity<EventPenaltyRecord, Integer> getIdentity() {
        return Keys.IDENTITY_EVENT_PENALTY;
    }

    @Override
    public UniqueKey<EventPenaltyRecord> getPrimaryKey() {
        return Keys.KEY_EVENT_PENALTY_PRIMARY;
    }

    @Override
    public List<UniqueKey<EventPenaltyRecord>> getKeys() {
        return Arrays.<UniqueKey<EventPenaltyRecord>>asList(Keys.KEY_EVENT_PENALTY_PRIMARY);
    }

    @Override
    public List<ForeignKey<EventPenaltyRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<EventPenaltyRecord, ?>>asList(Keys.FK_EVENT_PENALTY_GAME, Keys.FK__TEAM_PENALTY);
    }

    public Game game() {
        return new Game(this, Keys.FK_EVENT_PENALTY_GAME);
    }

    public Team team() {
        return new Team(this, Keys.FK__TEAM_PENALTY);
    }

    @Override
    public EventPenalty as(String alias) {
        return new EventPenalty(DSL.name(alias), this);
    }

    @Override
    public EventPenalty as(Name alias) {
        return new EventPenalty(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public EventPenalty rename(String name) {
        return new EventPenalty(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public EventPenalty rename(Name name) {
        return new EventPenalty(name, null);
    }

    // -------------------------------------------------------------------------
    // Row4 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row4<Integer, Integer, String, Integer> fieldsRow() {
        return (Row4) super.fieldsRow();
    }
}
