/*
 * This file is generated by jOOQ.
 */
package DB.Tables.tables;


import DB.Tables.Fwdb;
import DB.Tables.Keys;
import DB.Tables.enums.ManagerInTeamsAddCoach;
import DB.Tables.enums.ManagerInTeamsAddPlayer;
import DB.Tables.enums.ManagerInTeamsChangePositionPlayer;
import DB.Tables.enums.ManagerInTeamsChangeTeamJobCoach;
import DB.Tables.enums.ManagerInTeamsRemoveCoach;
import DB.Tables.enums.ManagerInTeamsRemovePlayer;
import DB.Tables.tables.records.ManagerInTeamsRecord;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row8;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ManagerInTeams extends TableImpl<ManagerInTeamsRecord> {

    private static final long serialVersionUID = 2053862272;

    /**
     * The reference instance of <code>fwdb.manager_in_teams</code>
     */
    public static final ManagerInTeams MANAGER_IN_TEAMS = new ManagerInTeams();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ManagerInTeamsRecord> getRecordType() {
        return ManagerInTeamsRecord.class;
    }

    /**
     * The column <code>fwdb.manager_in_teams.username</code>.
     */
    public final TableField<ManagerInTeamsRecord, String> USERNAME = createField(DSL.name("username"), org.jooq.impl.SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>fwdb.manager_in_teams.team_name</code>.
     */
    public final TableField<ManagerInTeamsRecord, String> TEAM_NAME = createField(DSL.name("team_name"), org.jooq.impl.SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>fwdb.manager_in_teams.REMOVE_PLAYER</code>.
     */
    public final TableField<ManagerInTeamsRecord, ManagerInTeamsRemovePlayer> REMOVE_PLAYER = createField(DSL.name("REMOVE_PLAYER"), org.jooq.impl.SQLDataType.VARCHAR(1).nullable(false).defaultValue(org.jooq.impl.DSL.field("'N'", org.jooq.impl.SQLDataType.VARCHAR)).asEnumDataType(DB.Tables.enums.ManagerInTeamsRemovePlayer.class), this, "");

    /**
     * The column <code>fwdb.manager_in_teams.ADD_PLAYER</code>.
     */
    public final TableField<ManagerInTeamsRecord, ManagerInTeamsAddPlayer> ADD_PLAYER = createField(DSL.name("ADD_PLAYER"), org.jooq.impl.SQLDataType.VARCHAR(1).nullable(false).defaultValue(org.jooq.impl.DSL.field("'N'", org.jooq.impl.SQLDataType.VARCHAR)).asEnumDataType(DB.Tables.enums.ManagerInTeamsAddPlayer.class), this, "");

    /**
     * The column <code>fwdb.manager_in_teams.CHANGE_POSITION_PLAYER</code>.
     */
    public final TableField<ManagerInTeamsRecord, ManagerInTeamsChangePositionPlayer> CHANGE_POSITION_PLAYER = createField(DSL.name("CHANGE_POSITION_PLAYER"), org.jooq.impl.SQLDataType.VARCHAR(1).nullable(false).defaultValue(org.jooq.impl.DSL.field("'N'", org.jooq.impl.SQLDataType.VARCHAR)).asEnumDataType(DB.Tables.enums.ManagerInTeamsChangePositionPlayer.class), this, "");

    /**
     * The column <code>fwdb.manager_in_teams.REMOVE_COACH</code>.
     */
    public final TableField<ManagerInTeamsRecord, ManagerInTeamsRemoveCoach> REMOVE_COACH = createField(DSL.name("REMOVE_COACH"), org.jooq.impl.SQLDataType.VARCHAR(1).nullable(false).defaultValue(org.jooq.impl.DSL.field("'N'", org.jooq.impl.SQLDataType.VARCHAR)).asEnumDataType(DB.Tables.enums.ManagerInTeamsRemoveCoach.class), this, "");

    /**
     * The column <code>fwdb.manager_in_teams.ADD_COACH</code>.
     */
    public final TableField<ManagerInTeamsRecord, ManagerInTeamsAddCoach> ADD_COACH = createField(DSL.name("ADD_COACH"), org.jooq.impl.SQLDataType.VARCHAR(1).nullable(false).defaultValue(org.jooq.impl.DSL.field("'N'", org.jooq.impl.SQLDataType.VARCHAR)).asEnumDataType(DB.Tables.enums.ManagerInTeamsAddCoach.class), this, "");

    /**
     * The column <code>fwdb.manager_in_teams.CHANGE_TEAM_JOB_COACH</code>.
     */
    public final TableField<ManagerInTeamsRecord, ManagerInTeamsChangeTeamJobCoach> CHANGE_TEAM_JOB_COACH = createField(DSL.name("CHANGE_TEAM_JOB_COACH"), org.jooq.impl.SQLDataType.VARCHAR(1).nullable(false).defaultValue(org.jooq.impl.DSL.field("'N'", org.jooq.impl.SQLDataType.VARCHAR)).asEnumDataType(DB.Tables.enums.ManagerInTeamsChangeTeamJobCoach.class), this, "");

    /**
     * Create a <code>fwdb.manager_in_teams</code> table reference
     */
    public ManagerInTeams() {
        this(DSL.name("manager_in_teams"), null);
    }

    /**
     * Create an aliased <code>fwdb.manager_in_teams</code> table reference
     */
    public ManagerInTeams(String alias) {
        this(DSL.name(alias), MANAGER_IN_TEAMS);
    }

    /**
     * Create an aliased <code>fwdb.manager_in_teams</code> table reference
     */
    public ManagerInTeams(Name alias) {
        this(alias, MANAGER_IN_TEAMS);
    }

    private ManagerInTeams(Name alias, Table<ManagerInTeamsRecord> aliased) {
        this(alias, aliased, null);
    }

    private ManagerInTeams(Name alias, Table<ManagerInTeamsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    public <O extends Record> ManagerInTeams(Table<O> child, ForeignKey<O, ManagerInTeamsRecord> key) {
        super(child, key, MANAGER_IN_TEAMS);
    }

    @Override
    public Schema getSchema() {
        return Fwdb.FWDB;
    }

    @Override
    public UniqueKey<ManagerInTeamsRecord> getPrimaryKey() {
        return Keys.KEY_MANAGER_IN_TEAMS_PRIMARY;
    }

    @Override
    public List<UniqueKey<ManagerInTeamsRecord>> getKeys() {
        return Arrays.<UniqueKey<ManagerInTeamsRecord>>asList(Keys.KEY_MANAGER_IN_TEAMS_PRIMARY);
    }

    @Override
    public List<ForeignKey<ManagerInTeamsRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<ManagerInTeamsRecord, ?>>asList(Keys.FK_MANAGED_TEAMS_TEAM);
    }

    public Team team() {
        return new Team(this, Keys.FK_MANAGED_TEAMS_TEAM);
    }

    @Override
    public ManagerInTeams as(String alias) {
        return new ManagerInTeams(DSL.name(alias), this);
    }

    @Override
    public ManagerInTeams as(Name alias) {
        return new ManagerInTeams(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ManagerInTeams rename(String name) {
        return new ManagerInTeams(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ManagerInTeams rename(Name name) {
        return new ManagerInTeams(name, null);
    }

    // -------------------------------------------------------------------------
    // Row8 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row8<String, String, ManagerInTeamsRemovePlayer, ManagerInTeamsAddPlayer, ManagerInTeamsChangePositionPlayer, ManagerInTeamsRemoveCoach, ManagerInTeamsAddCoach, ManagerInTeamsChangeTeamJobCoach> fieldsRow() {
        return (Row8) super.fieldsRow();
    }
}
