/*
 * This file is generated by jOOQ.
 */
package DB.Tables_Test;


import DB.Tables_Test.tables.Alert;
import DB.Tables_Test.tables.AssociationRepresentative;
import DB.Tables_Test.tables.Coach;
import DB.Tables_Test.tables.CoachInTeam;
import DB.Tables_Test.tables.EventCard;
import DB.Tables_Test.tables.EventGoal;
import DB.Tables_Test.tables.EventInjury;
import DB.Tables_Test.tables.EventOffside;
import DB.Tables_Test.tables.EventPenalty;
import DB.Tables_Test.tables.EventSwitchPlayers;
import DB.Tables_Test.tables.Game;
import DB.Tables_Test.tables.GamesInSeason;
import DB.Tables_Test.tables.League;
import DB.Tables_Test.tables.ManagerInTeams;
import DB.Tables_Test.tables.OwnedTeams;
import DB.Tables_Test.tables.Player;
import DB.Tables_Test.tables.PlayerInTeam;
import DB.Tables_Test.tables.PointsPolicy;
import DB.Tables_Test.tables.Referee;
import DB.Tables_Test.tables.RefereeInGame;
import DB.Tables_Test.tables.RefereeInSeason;
import DB.Tables_Test.tables.SchedulingPolicy;
import DB.Tables_Test.tables.Season;
import DB.Tables_Test.tables.Stadium;
import DB.Tables_Test.tables.StadiumHomeTeams;
import DB.Tables_Test.tables.SystemAdmin;
import DB.Tables_Test.tables.Systemuser;
import DB.Tables_Test.tables.Team;
import DB.Tables_Test.tables.TeamManager;
import DB.Tables_Test.tables.TeamOwner;
import DB.Tables_Test.tables.TeamsInSeason;
import DB.Tables_Test.tables.UserComplaint;
import DB.Tables_Test.tables.UserRoles;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FwdbTest extends SchemaImpl {

    private static final long serialVersionUID = -138432874;

    /**
     * The reference instance of <code>fwdb_test</code>
     */
    public static final FwdbTest FWDB_TEST = new FwdbTest();

    /**
     * The table <code>fwdb_test.alert</code>.
     */
    public final Alert ALERT = Alert.ALERT;

    /**
     * The table <code>fwdb_test.association_representative</code>.
     */
    public final AssociationRepresentative ASSOCIATION_REPRESENTATIVE = AssociationRepresentative.ASSOCIATION_REPRESENTATIVE;

    /**
     * The table <code>fwdb_test.coach</code>.
     */
    public final Coach COACH = Coach.COACH;

    /**
     * The table <code>fwdb_test.coach_in_team</code>.
     */
    public final CoachInTeam COACH_IN_TEAM = CoachInTeam.COACH_IN_TEAM;

    /**
     * The table <code>fwdb_test.event_card</code>.
     */
    public final EventCard EVENT_CARD = EventCard.EVENT_CARD;

    /**
     * The table <code>fwdb_test.event_goal</code>.
     */
    public final EventGoal EVENT_GOAL = EventGoal.EVENT_GOAL;

    /**
     * The table <code>fwdb_test.event_injury</code>.
     */
    public final EventInjury EVENT_INJURY = EventInjury.EVENT_INJURY;

    /**
     * The table <code>fwdb_test.event_offside</code>.
     */
    public final EventOffside EVENT_OFFSIDE = EventOffside.EVENT_OFFSIDE;

    /**
     * The table <code>fwdb_test.event_penalty</code>.
     */
    public final EventPenalty EVENT_PENALTY = EventPenalty.EVENT_PENALTY;

    /**
     * The table <code>fwdb_test.event_switch_players</code>.
     */
    public final EventSwitchPlayers EVENT_SWITCH_PLAYERS = EventSwitchPlayers.EVENT_SWITCH_PLAYERS;

    /**
     * The table <code>fwdb_test.game</code>.
     */
    public final Game GAME = Game.GAME;

    /**
     * The table <code>fwdb_test.games_in_season</code>.
     */
    public final GamesInSeason GAMES_IN_SEASON = GamesInSeason.GAMES_IN_SEASON;

    /**
     * The table <code>fwdb_test.league</code>.
     */
    public final League LEAGUE = League.LEAGUE;

    /**
     * The table <code>fwdb_test.manager_in_teams</code>.
     */
    public final ManagerInTeams MANAGER_IN_TEAMS = ManagerInTeams.MANAGER_IN_TEAMS;

    /**
     * The table <code>fwdb_test.owned_teams</code>.
     */
    public final OwnedTeams OWNED_TEAMS = OwnedTeams.OWNED_TEAMS;

    /**
     * The table <code>fwdb_test.player</code>.
     */
    public final Player PLAYER = Player.PLAYER;

    /**
     * The table <code>fwdb_test.player_in_team</code>.
     */
    public final PlayerInTeam PLAYER_IN_TEAM = PlayerInTeam.PLAYER_IN_TEAM;

    /**
     * The table <code>fwdb_test.points_policy</code>.
     */
    public final PointsPolicy POINTS_POLICY = PointsPolicy.POINTS_POLICY;

    /**
     * The table <code>fwdb_test.referee</code>.
     */
    public final Referee REFEREE = Referee.REFEREE;

    /**
     * The table <code>fwdb_test.referee_in_game</code>.
     */
    public final RefereeInGame REFEREE_IN_GAME = RefereeInGame.REFEREE_IN_GAME;

    /**
     * The table <code>fwdb_test.referee_in_season</code>.
     */
    public final RefereeInSeason REFEREE_IN_SEASON = RefereeInSeason.REFEREE_IN_SEASON;

    /**
     * The table <code>fwdb_test.scheduling_policy</code>.
     */
    public final SchedulingPolicy SCHEDULING_POLICY = SchedulingPolicy.SCHEDULING_POLICY;

    /**
     * The table <code>fwdb_test.season</code>.
     */
    public final Season SEASON = Season.SEASON;

    /**
     * The table <code>fwdb_test.stadium</code>.
     */
    public final Stadium STADIUM = Stadium.STADIUM;

    /**
     * The table <code>fwdb_test.stadium_home_teams</code>.
     */
    public final StadiumHomeTeams STADIUM_HOME_TEAMS = StadiumHomeTeams.STADIUM_HOME_TEAMS;

    /**
     * The table <code>fwdb_test.system_admin</code>.
     */
    public final SystemAdmin SYSTEM_ADMIN = SystemAdmin.SYSTEM_ADMIN;

    /**
     * The table <code>fwdb_test.systemuser</code>.
     */
    public final Systemuser SYSTEMUSER = Systemuser.SYSTEMUSER;

    /**
     * The table <code>fwdb_test.team</code>.
     */
    public final Team TEAM = Team.TEAM;

    /**
     * The table <code>fwdb_test.team_manager</code>.
     */
    public final TeamManager TEAM_MANAGER = TeamManager.TEAM_MANAGER;

    /**
     * The table <code>fwdb_test.team_owner</code>.
     */
    public final TeamOwner TEAM_OWNER = TeamOwner.TEAM_OWNER;

    /**
     * The table <code>fwdb_test.teams_in_season</code>.
     */
    public final TeamsInSeason TEAMS_IN_SEASON = TeamsInSeason.TEAMS_IN_SEASON;

    /**
     * The table <code>fwdb_test.user_complaint</code>.
     */
    public final UserComplaint USER_COMPLAINT = UserComplaint.USER_COMPLAINT;

    /**
     * The table <code>fwdb_test.user_roles</code>.
     */
    public final UserRoles USER_ROLES = UserRoles.USER_ROLES;

    /**
     * No further instances allowed
     */
    private FwdbTest() {
        super("fwdb_test", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            Alert.ALERT,
            AssociationRepresentative.ASSOCIATION_REPRESENTATIVE,
            Coach.COACH,
            CoachInTeam.COACH_IN_TEAM,
            EventCard.EVENT_CARD,
            EventGoal.EVENT_GOAL,
            EventInjury.EVENT_INJURY,
            EventOffside.EVENT_OFFSIDE,
            EventPenalty.EVENT_PENALTY,
            EventSwitchPlayers.EVENT_SWITCH_PLAYERS,
            Game.GAME,
            GamesInSeason.GAMES_IN_SEASON,
            League.LEAGUE,
            ManagerInTeams.MANAGER_IN_TEAMS,
            OwnedTeams.OWNED_TEAMS,
            Player.PLAYER,
            PlayerInTeam.PLAYER_IN_TEAM,
            PointsPolicy.POINTS_POLICY,
            Referee.REFEREE,
            RefereeInGame.REFEREE_IN_GAME,
            RefereeInSeason.REFEREE_IN_SEASON,
            SchedulingPolicy.SCHEDULING_POLICY,
            Season.SEASON,
            Stadium.STADIUM,
            StadiumHomeTeams.STADIUM_HOME_TEAMS,
            SystemAdmin.SYSTEM_ADMIN,
            Systemuser.SYSTEMUSER,
            Team.TEAM,
            TeamManager.TEAM_MANAGER,
            TeamOwner.TEAM_OWNER,
            TeamsInSeason.TEAMS_IN_SEASON,
            UserComplaint.USER_COMPLAINT,
            UserRoles.USER_ROLES);
    }
}
