/*
 * This file is generated by jOOQ.
 */
package DB.Tables_Test;


import DB.Tables_Test.tables.Season;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>fwdb_test</code> schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index SEASON_LEAGUE_NAME = Indexes0.SEASON_LEAGUE_NAME;
    public static final Index SEASON_YEARS = Indexes0.SEASON_YEARS;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index SEASON_LEAGUE_NAME = Internal.createIndex("league_name", Season.SEASON, new OrderField[] { Season.SEASON.LEAGUE_NAME }, false);
        public static Index SEASON_YEARS = Internal.createIndex("years", Season.SEASON, new OrderField[] { Season.SEASON.YEARS }, false);
    }
}
