/*
 * This file is generated by jOOQ.
 */
package DB.Tables_Test;


import DB.Tables_Test.tables.Alert;
import DB.Tables_Test.tables.AssociationRepresentative;
import DB.Tables_Test.tables.Coach;
import DB.Tables_Test.tables.CoachInTeam;
import DB.Tables_Test.tables.ErrorLog;
import DB.Tables_Test.tables.EventCard;
import DB.Tables_Test.tables.EventGoal;
import DB.Tables_Test.tables.EventInjury;
import DB.Tables_Test.tables.EventLog;
import DB.Tables_Test.tables.EventOffside;
import DB.Tables_Test.tables.EventPenalty;
import DB.Tables_Test.tables.EventSwitchPlayers;
import DB.Tables_Test.tables.Game;
import DB.Tables_Test.tables.GamesInSeason;
import DB.Tables_Test.tables.League;
import DB.Tables_Test.tables.ManagerInTeams;
import DB.Tables_Test.tables.OwnedTeams;
import DB.Tables_Test.tables.Player;
import DB.Tables_Test.tables.PlayerInTeam;
import DB.Tables_Test.tables.PointsPolicy;
import DB.Tables_Test.tables.Referee;
import DB.Tables_Test.tables.RefereeInGame;
import DB.Tables_Test.tables.RefereeInSeason;
import DB.Tables_Test.tables.SchedulingPolicy;
import DB.Tables_Test.tables.Season;
import DB.Tables_Test.tables.Stadium;
import DB.Tables_Test.tables.StadiumHomeTeams;
import DB.Tables_Test.tables.SystemAdmin;
import DB.Tables_Test.tables.Systemuser;
import DB.Tables_Test.tables.Team;
import DB.Tables_Test.tables.TeamManager;
import DB.Tables_Test.tables.TeamOwner;
import DB.Tables_Test.tables.TeamsInSeason;
import DB.Tables_Test.tables.UserComplaint;
import DB.Tables_Test.tables.UserRoles;


/**
 * Convenience access to all tables in fwdb_test
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>fwdb_test.alert</code>.
     */
    public static final Alert ALERT = Alert.ALERT;

    /**
     * The table <code>fwdb_test.association_representative</code>.
     */
    public static final AssociationRepresentative ASSOCIATION_REPRESENTATIVE = AssociationRepresentative.ASSOCIATION_REPRESENTATIVE;

    /**
     * The table <code>fwdb_test.coach</code>.
     */
    public static final Coach COACH = Coach.COACH;

    /**
     * The table <code>fwdb_test.coach_in_team</code>.
     */
    public static final CoachInTeam COACH_IN_TEAM = CoachInTeam.COACH_IN_TEAM;

    /**
     * The table <code>fwdb_test.error_log</code>.
     */
    public static final ErrorLog ERROR_LOG = ErrorLog.ERROR_LOG;

    /**
     * The table <code>fwdb_test.event_card</code>.
     */
    public static final EventCard EVENT_CARD = EventCard.EVENT_CARD;

    /**
     * The table <code>fwdb_test.event_goal</code>.
     */
    public static final EventGoal EVENT_GOAL = EventGoal.EVENT_GOAL;

    /**
     * The table <code>fwdb_test.event_injury</code>.
     */
    public static final EventInjury EVENT_INJURY = EventInjury.EVENT_INJURY;

    /**
     * The table <code>fwdb_test.event_log</code>.
     */
    public static final EventLog EVENT_LOG = EventLog.EVENT_LOG;

    /**
     * The table <code>fwdb_test.event_offside</code>.
     */
    public static final EventOffside EVENT_OFFSIDE = EventOffside.EVENT_OFFSIDE;

    /**
     * The table <code>fwdb_test.event_penalty</code>.
     */
    public static final EventPenalty EVENT_PENALTY = EventPenalty.EVENT_PENALTY;

    /**
     * The table <code>fwdb_test.event_switch_players</code>.
     */
    public static final EventSwitchPlayers EVENT_SWITCH_PLAYERS = EventSwitchPlayers.EVENT_SWITCH_PLAYERS;

    /**
     * The table <code>fwdb_test.game</code>.
     */
    public static final Game GAME = Game.GAME;

    /**
     * The table <code>fwdb_test.games_in_season</code>.
     */
    public static final GamesInSeason GAMES_IN_SEASON = GamesInSeason.GAMES_IN_SEASON;

    /**
     * The table <code>fwdb_test.league</code>.
     */
    public static final League LEAGUE = League.LEAGUE;

    /**
     * The table <code>fwdb_test.manager_in_teams</code>.
     */
    public static final ManagerInTeams MANAGER_IN_TEAMS = ManagerInTeams.MANAGER_IN_TEAMS;

    /**
     * The table <code>fwdb_test.owned_teams</code>.
     */
    public static final OwnedTeams OWNED_TEAMS = OwnedTeams.OWNED_TEAMS;

    /**
     * The table <code>fwdb_test.player</code>.
     */
    public static final Player PLAYER = Player.PLAYER;

    /**
     * The table <code>fwdb_test.player_in_team</code>.
     */
    public static final PlayerInTeam PLAYER_IN_TEAM = PlayerInTeam.PLAYER_IN_TEAM;

    /**
     * The table <code>fwdb_test.points_policy</code>.
     */
    public static final PointsPolicy POINTS_POLICY = PointsPolicy.POINTS_POLICY;

    /**
     * The table <code>fwdb_test.referee</code>.
     */
    public static final Referee REFEREE = Referee.REFEREE;

    /**
     * The table <code>fwdb_test.referee_in_game</code>.
     */
    public static final RefereeInGame REFEREE_IN_GAME = RefereeInGame.REFEREE_IN_GAME;

    /**
     * The table <code>fwdb_test.referee_in_season</code>.
     */
    public static final RefereeInSeason REFEREE_IN_SEASON = RefereeInSeason.REFEREE_IN_SEASON;

    /**
     * The table <code>fwdb_test.scheduling_policy</code>.
     */
    public static final SchedulingPolicy SCHEDULING_POLICY = SchedulingPolicy.SCHEDULING_POLICY;

    /**
     * The table <code>fwdb_test.season</code>.
     */
    public static final Season SEASON = Season.SEASON;

    /**
     * The table <code>fwdb_test.stadium</code>.
     */
    public static final Stadium STADIUM = Stadium.STADIUM;

    /**
     * The table <code>fwdb_test.stadium_home_teams</code>.
     */
    public static final StadiumHomeTeams STADIUM_HOME_TEAMS = StadiumHomeTeams.STADIUM_HOME_TEAMS;

    /**
     * The table <code>fwdb_test.system_admin</code>.
     */
    public static final SystemAdmin SYSTEM_ADMIN = SystemAdmin.SYSTEM_ADMIN;

    /**
     * The table <code>fwdb_test.systemuser</code>.
     */
    public static final Systemuser SYSTEMUSER = Systemuser.SYSTEMUSER;

    /**
     * The table <code>fwdb_test.team</code>.
     */
    public static final Team TEAM = Team.TEAM;

    /**
     * The table <code>fwdb_test.team_manager</code>.
     */
    public static final TeamManager TEAM_MANAGER = TeamManager.TEAM_MANAGER;

    /**
     * The table <code>fwdb_test.team_owner</code>.
     */
    public static final TeamOwner TEAM_OWNER = TeamOwner.TEAM_OWNER;

    /**
     * The table <code>fwdb_test.teams_in_season</code>.
     */
    public static final TeamsInSeason TEAMS_IN_SEASON = TeamsInSeason.TEAMS_IN_SEASON;

    /**
     * The table <code>fwdb_test.user_complaint</code>.
     */
    public static final UserComplaint USER_COMPLAINT = UserComplaint.USER_COMPLAINT;

    /**
     * The table <code>fwdb_test.user_roles</code>.
     */
    public static final UserRoles USER_ROLES = UserRoles.USER_ROLES;
}
