# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Shutdown Ubuntu MySQL (SUDO)
        run: sudo service mysql stop # Shutdown the Default MySQL, "sudo" is necessary, please not remove it

      - name: Start MariaDB
        uses: getong/mariadb-action@v1.1
        with:
          # The port of host
          host port: 3306 # optional, default is 3306
          # The port of container
          container port: 3306 # optional, default is 3306
          # --character-set-server - The character set of MySQL server
          character set server: 'utf8mb4'# optional, default is utf8mb4
          # MYSQL_ROOT_PASSWORD - root superuser password ??????
          mysql root password: 'foot123Ball!'
          # MYSQL_DATABASE - name for the default database that is created
          mysql database: 'fwdb_test' # optional, default is

      - uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Build with Maven
        run: mvn -B -DskipTests=true clean package --file pom.xml

      - name: Run All Unit Tests with Maven
        run: mvn test --file pom.xml
      
